# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5adfa08c229b8e505fe25fac79038755d6beaebb48a192c59e0d738ff1cbeebf7c59b44b5c69360373f7a082d9ede3346f6bb40a136606ccb0599bb300943cf1

test:
  secret_key_base: f0a37415635b8f7c8da35982bad5eab3b8a32bdf92b45ffdff5c62f04e3134914e3a790a8167265ec9eb5f2ef6ec8549eb658d55ee8d99a40fd9d337e89ce7fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
